name: Full Deployment
run-name: Create Env by Terraform

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-southeast-2                   

permissions:
  contents: read

jobs:
  CreateEnvTerraform:
    name: Create Env By Terraform
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: init terraform
      run: terraform init 
    - name: plan terraform
      run: terraform plan
    - name: apply terraform
      run: terraform apply --auto-approve
    - name: destroy terraform 
      run: terraform destroy --auto-approve
  CreateEnvByCloudFormation:
    needs: CreateEnvTerraform 
    name: Create Env by CloudFormation
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Create env by CloudFormation
      run: aws cloudformation deploy --template-file cf.yaml --stack-name demoenv
    - name: Delete env by Cloudformation
      run: aws cloudformation delete-stack --stackname demoenv
